### PR TITLE
add CI suite

### LINKED ISSUE #4: do you want CI ?
I can integrate Travis CI and molecule with testing in docker for this role if you want :)

Examples of such config are in:
- https://github.com/cloudalchemy/ansible-prometheus
- https://github.com/cloudalchemy/ansible-grafana

Do you want it?

### PR DESCRIPTION
**Pull request by paulfantom**
Resolves #4

### CODE REVIEW

**Comment by paulfantom** [comment]
@jffz can you enable travis ci for this repository and PRs?

**Comment by paulfantom** [comment]
@jffz ping

**Comment by jffz** [comment]
Hi,

Finally accepted your PR but looks like the ansible lint is angry.

https://travis-ci.org/jffz/ansible-netdata/jobs/363795041

I'm not sure if we'd like to make the installation an handler. How do you want ot handle htis ?

**Comment by paulfantom** [comment]
@jffz this way: #7 :smile:

**Pull request merged**
